config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  get 'books/new', to: 'books#new'
  post 'books/create', to: 'books#create', as: 'c_book'

  get 'loans/new', to: 'loans#new'
  post 'loans/create', to: 'loans#create', as: 'c_loan'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :loans
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :book
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:en_estante]
      @books = Book.where(state: false)
    elsif params[:prestados]
      @books = Book.where(state: true)
    else
      @books = Book.all
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :state)
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  def new
    @loan = Loan.new
    @book_name = Book.find(params[:book_id]).title
  end

  def create
    @loan = Loan.new(loan_params)
    @loan.save
    Book.find(@loan.book_id).update(state: true)
    redirect_to root_path
  end

  private

  def loan_params
    params.require(:loan).permit(:book_id, :loan_beginning, :loan_end)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/loans_helper.rb
module LoansHelper
    
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/index.html.erb
<form>
    <input type="submit", value='prestados' name="prestados">
    <input type="submit", value='en estante' name="en_estante">
    <input type="submit", value='todos' name="todos">
</form>

<% if @books.size == 0 %>
    <h3> No hay libros en la biblioteca </h3>
<% else %>
    <% @books.each do |i| %>
        <ul>
            <li> Titulo: <%= i.title %> </li>
            <li> Autor: <%= i.author %> </li>
            <% if i.state == false %>
                <li> estado: en estante || <%= link_to 'prestar', loans_new_path(:book_id => i.id) %> </li>
            <% else %>
                <li> estado: prestado </li>
                <li> detalle prestamo: <% i.loans.each do |x| %>
                    <ul>
                        <li> fecha prestamo: <%= x.loan_beginning %> </li>
                        <li> fecha devolucion: <%= x.loan_end %> </li>
                    </ul>
                <% end %> </li>
            <% end %>
        </ul>
    <% end %>
<% end %>

<%= link_to 'crear nuevo libro', books_new_path %>

app/views/books/new.html.erb
<%= form_with(url: c_book_path, model: @book, local: true) do |f| %>
    <%= f.text_field :title, placeholder: 'titulo' %>
    <%= f.text_field :author, placeholder: 'autor' %>
    <%= f.submit 'crear libro' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biblioteca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/loans/create.html.erb
<%= @libro %>

app/views/loans/new.html.erb
<%= form_with(url: c_loan_path(:book_id => params[:book_id]), model: @loan, local: true) do |f| %>
    <%= f.number_field :book_id, value: params[:book_id], type: 'hidden'  %>
    <div>
        <h3> Libro a prestar </h3>
        <%= f.text_field :name, value: @book_name %>
    </div>

    <div>
        <h3> fecha prestamo </h3>
        <%= f.date_field :loan_beginning %>
    </div>

    <div>
        <h3> fecha devolucion </h3> 
        <%= f.date_field :loan_end %>
    </div>

    <%= f.submit 'prestar libro' %>
<% end %>